print(f'\033[33m{"—"*30:^30}\033[m')
print(f'\033[36m{"EXERCÍCIO Nº 9":^30}\033[m')
print(f'\033[33m{"—"*30:^30}\033[m')
print('Veja a tabuada de um número!')
num = int(input('Digite um número: '))
print(f'\n Tabuada do {num}:')
print(f' 0 x {num} = {0 * num}')
print(f' 1 x {num} = {1 * num}')
print(f' 2 x {num} = {2 * num}')
print(f' 3 x {num} = {3 * num}')
print(f' 4 x {num} = {4 * num}')
print(f' 5 x {num} = {5 * num}')
print(f' 6 x {num} = {6 * num}')
print(f' 7 x {num} = {7 * num}')
print(f' 8 x {num} = {8 * num}')
print(f' 9 x {num} = {9 * num}')
print(f'10 x {num} = {10 * num}')